#MIT License

#Copyright (c) 2024-2024 Peter Kirmeier

#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:

#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.

#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.

# https://aka.ms/yaml
# https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/?view=azure-pipelines&viewFallbackFrom=azure-devops
# https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops
# RuntimeRID values: https://docs.microsoft.com/en-us/dotnet/core/rid-catalog
# Available Software on Agents: https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software

trigger:
- v2.x_Avalonia

stages:
- stage: Build

  jobs:
  - job:
    strategy:
      maxParallel: 4
      matrix:
# Most Used
        win-x64:
          PoolVmImg: 'windows-latest'
          RuntimeRID: 'win-x64'
          PlatformType: 'Desktop'
          SelfContained: 'false'
        linux-x64:
          PoolVmImg: 'ubuntu-latest'
          RuntimeRID: 'linux-x64'
          PlatformType: 'Desktop'
          SelfContained: 'false'
        osx-x64:
          PoolVmImg: 'macOS-latest'
          RuntimeRID: 'osx-x64'
          PlatformType: 'Desktop'
          SelfContained: 'false'
# Windows
#       win-x86:
#         PoolVmImg: 'windows-latest'
#         RuntimeRID: 'win-x86'
#         PlatformType: 'Desktop'
#         SelfContained: 'false'
#       win-arm:
#         PoolVmImg: 'windows-latest'
#         RuntimeRID: 'win-arm'
#         PlatformType: 'Desktop'
#         SelfContained: 'false'
#       win-arm64:
#         PoolVmImg: 'windows-latest'
#         RuntimeRID: 'win-arm64'
#         PlatformType: 'Desktop'
#         SelfContained: 'false'
# Linux
#       linux-musl-x64:
#         PoolVmImg: 'ubuntu-latest'
#         RuntimeRID: 'linux-musl-x64'
#         PlatformType: 'Desktop'
#         SelfContained: 'false'
#       linux-arm:
#         PoolVmImg: 'ubuntu-latest'
#         RuntimeRID: 'linux-arm'
#         PlatformType: 'Desktop'
#         SelfContained: 'false'
#       linux-arm64:
#         PoolVmImg: 'ubuntu-latest'
#         RuntimeRID: 'linux-arm64'
#         PlatformType: 'Desktop'
#         SelfContained: 'false'

    variables:
      buildConfiguration: 'Release'
      targetFramework: 'net8.0'

    pool:
      vmImage: '$(PoolVmImg)'

    steps:

# Available versions: https://github.com/dotnet/core/blob/main/release-notes/releases-index.json
    - task: UseDotNet@2
      displayName: 'Install .NET 8'
      inputs:
        version: '8.x'

# Available versions: https://dist.nuget.org/tools.json
    - task: NuGetToolInstaller@1
      displayName: 'Install NuGet 6'
      inputs:
        versionSpec: '6.x'

# example:  dotnet publish --configuration Release --runtime win-x64   --framework net8.0 --self-contained false SystemTrayMenu.csproj
# example:  dotnet publish --configuration Release --runtime linux-x64 --framework net8.0 --self-contained true  SystemTrayMenu.csproj

    - task: DotNetCoreCLI@2
      displayName: 'DotNet Publish'
      inputs:
        command: 'publish'
        arguments: '--configuration $(buildConfiguration) --runtime $(RuntimeRID) --framework $(targetFramework) --self-contained $(SelfContained)'
        publishWebProjects: false
        zipAfterPublish: false
        projects: '$(Build.DefinitionName).csproj'

    - task: Bash@3
      displayName: 'Dump file tree'
      inputs:
        targetType: 'inline'
        script: |
          echo "Listing '$(Build.SourcesDirectory)' ..."
          find -L . -type f

    - task: ArchiveFiles@2
      condition: startsWith(variables['RuntimeRID'], 'win-')
      displayName: 'Archive ZIP'
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/bin/AnyCPU/$(buildConfiguration)/$(targetFramework)/$(RuntimeRID)/publish/'
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.DefinitionName).$(System.JobName)-v2-PreRelease.zip'
        archiveType: 'zip'
        replaceExistingArchive: true
        verbose: true

    - task: ArchiveFiles@2
      condition: or(startsWith(variables['RuntimeRID'], 'linux-'), startsWith(variables['RuntimeRID'], 'osx-'))
      displayName: 'Archive TAR.GZ'
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/bin/AnyCPU/$(buildConfiguration)/$(targetFramework)/$(RuntimeRID)/publish/'
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.DefinitionName).$(System.JobName)-v2-PreRelease.tar.gz'
        archiveType: 'tar'
        tarCompression: 'gz'
        replaceExistingArchive: true
        verbose: true

#https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops

#- stage: Deploy
#  dependsOn: Build
#
# https://docs.microsoft.com/de-de/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#use-outputs-in-a-different-stage
#
#  jobs:
#  - job: Store
#    displayName: 'Deploy Artifacts'
#    pool:
#      vmImage: 'windows-latest'
#
#    steps:

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: PreRelease'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        publishLocation: 'Container'
        ArtifactName: 'PreRelease'
